FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libelf-dev git

COPY . /repo
WORKDIR /repo
RUN make -j8 buildid

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libelf-dev
COPY --from=builder /repo/buildid /
